development: &development
  adapter: postgresql
  encoding: unicode
  database: dispatch_app_development
  pool: 5
  # username: postgres
  # password:


test: &test
  <<: *development
  database: dispatch_app_test


production:
  <<: *development
  database: dispatch_app_test
cucumber:
  <<: *test
